In [ ]:
a = int(input("하나의 수 입력: "))
b = int(input("수를 하나 더 입력: "))
if a < b:
  print(a, "는 ", b, "보다 작아요.")
else:
  print(a, "는(은)", b, "와 같거나 커요.")

하나의 수 입력: 20
수를 하나 더 입력: 10
20 는(은) 10 와 같거나 커요.


In [ ]:
a = [1, 2, 3]
print(a)

[1, 2, 3]


In [ ]:
# 배열
a[0]

1

In [ ]:
a[2]

3

In [ ]:
name = ["도은엽","정용현","김보혁"]
print(name)

['도은엽', '정용현', '김보혁']


In [ ]:
print(name[0], name[1], name[2])

도은엽 정용현 김보혁


In [ ]:
print(name[0])
print(name[1])
print(name[2])

도은엽
정용현
김보혁


In [ ]:
for num in a:
  print(num)

1
2
3


In [ ]:
for num in name:
  print(num)

도은엽
정용현
김보혁


In [ ]:
score = [[100, 98, 95],
         [95, 93, 98]]
print(score)

[[100, 98, 95], [95, 93, 98]]


In [ ]:
score_a = [[100, 98, 95], [95, 93, 98]]

In [ ]:
print(score[0])

[100, 98, 95]


In [ ]:
print(score[0][0])

100


In [ ]:
print(score[0][0], score[0][1], score[0][2],
      score[1][0], score[1][1], score[1][2])

100 98 95 95 93 98


In [ ]:
for 행 in score:
  print(행)

[100, 98, 95]
[95, 93, 98]


In [ ]:
for 행 in score:
  for 열 in 행:
    print(열)

100
98
95
95
93
98


In [ ]:
import numpy as np
anp = np.array(score) # score를 배열로 선언
print(anp)
anp

[[100  98  95]
 [ 95  93  98]]


array([[100,  98,  95],
       [ 95,  93,  98]])

In [ ]:
score[0][1]

98

In [ ]:
anp[0][1]

98

In [ ]:
anp[0,1]

98

In [ ]:
# 배열 생성
vec = np.arange(10)
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
vec2 = np.arange(2, 10)

In [ ]:
vec2

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
vec3 = np.arange(1, 10, 2)

In [ ]:
vec3

array([1, 3, 5, 7, 9])

In [ ]:
# 벡터 크기 계산
v = np.arange(3, 5)
v

array([3, 4])

In [ ]:
vsquare = np.square(v)
vsquare

array([ 9, 16])

In [ ]:
vsum = np.sum(vsquare)
vsum

25

In [ ]:
vroot = np.sqrt(vsum)
vroot

5.0

In [ ]:
np.hypot(v[0], v[1])

5.0

In [ ]:
np.linalg.norm(v)

5.0

In [ ]:
# 행렬
matrix = np.array([[100, 98, 95],
                   [95, 93, 98]])
matrix

array([[100,  98,  95],
       [ 95,  93,  98]])

In [ ]:
matrix2 = np.array([[1], [2]])
matrix2

array([[1],
       [2]])

In [ ]:
vector1 = np.array([1, 2])
vector1

array([1, 2])

In [ ]:
#배열의 축소
a33 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
a33

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a33.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#다차원 배열의 검색
v = np.array([1,2,3,4,5])

In [ ]:
v[0]

1

In [ ]:
v[-1]

5

In [ ]:
v[-2]

4

In [ ]:
m = np.array([[1,2,3,4,5],
              [6,7,8,9,10]])

In [ ]:
m[0]

array([1, 2, 3, 4, 5])

In [ ]:
m[1]

array([ 6,  7,  8,  9, 10])

In [ ]:
m[-1]

array([ 6,  7,  8,  9, 10])

In [ ]:
m[-2]

array([1, 2, 3, 4, 5])

In [ ]:
m[1,3]

9

In [ ]:
# 엑셀 csv 자료를 구글코랩에 업로드
from google.colab import files
up = files.upload()

Saving bank.csv to bank (1).csv


In [ ]:
import pandas as pd
bank_df = pd.read_csv('bank.csv', sep=',')
bank_df.head()

age          job  marital  education default  balance housing loan contact  \
0   58   management  married   tertiary      no     2143     yes   no     NaN   
1   36   technician   single  secondary      no      265     yes  yes     NaN   
2   25  blue-collar  married  secondary      no       -7     yes   no     NaN   
3   53   technician  married  secondary      no       -3      no   no     NaN   
4   24   technician   single  secondary      no     -103     yes  yes     NaN   

   day month  duration  campaign  pdays  previous poutcome   y  
0    5   may       261         1     -1         0      NaN  no  
1    5   may       348         1     -1         0      NaN  no  
2    5   may       365         1     -1         0      NaN  no  
3    5   may      1666         1     -1         0      NaN  no  
4    5   may       145         1     -1         0      NaN  no